# Generated by Django 6.0.4 on 2026-05-06 10:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MistakeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_answer', models.CharField(max_length=20)),
                ('correct_answer', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=150)),
                ('source', models.CharField(choices=[('quiz', 'Quiz'), ('battle', 'Battle')], default='quiz', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_logs', to='quizzes.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mistake_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoursesAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('new_enrollments', models.PositiveIntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='courses.course')),
            ],
            options={
                'db_table': 'course_analytics',
                'ordering': ['-date'],
                'unique_together': {('course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MistakeAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=150)),
                ('mistake_count', models.PositiveIntegerField(default=0)),
                ('suggestion', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistake_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mistake_analyses',
                'ordering': ['-mistake_count'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
