# Generated by Django 6.0.4 on 2026-05-07 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresttoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PasswordRestToken',
            new_name='PasswordResetToken',
        ),
    ]
