# Generated by Django 6.0.4 on 2026-05-14 07:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_passwordresttoken_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile'),
        ),
    ]
