# Generated by Django 6.0.4 on 2026-05-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_alter_battlequestion_battle'),
    ]

    operations = [
        migrations.AddField(
            model_name='battleroom',
            name='invite_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
